ref: "/public/home/lizw/data/IMPORTANT_genome/arabidopsis/col-CEN/dna/Col-CEN_v1.2.fasta"
fastq1: "/public/home/lizw/task/pore_c/DpnII_hic2/4DN_cool/fastq/SRR1029605.1_R1.fastq.gz"
fastq2: "/public/home/lizw/task/pore_c/DpnII_hic2/4DN_cool/fastq/SRR1029605.1_R1.fastq.gz"
MAPQ: [1,10,30]
resolution: 1000
